create table if not exists public.wardrobe (
  id bigint generated by default as identity primary key,
  name text not null,
  product_name text,
  brand text,
  type text not null check (type in ('top', 'bottom', 'outerwear', 'dress', 'shoes')),
  subtype text,
  color text,
  season text,
  capsule boolean not null default false,
  notes text,
  type_order int generated always as (
    case type
      when 'top' then 1
      when 'bottom' then 2
      when 'outerwear' then 3
      when 'dress' then 4
      when 'shoes' then 5
      else 999
    end
  ) stored,
  subtype_order int generated always as (
    case
      when subtype = 'tank' then 1
      when subtype = 'baby tee' then 2
      when subtype in ('shirt', 'button-down', 'blouse') then 3
      else 9
    end
  ) stored,
  created_at timestamptz not null default now()
);

create or replace view public.wardrobe_capsule as
select
  name,
  brand,
  capsule,
  type,
  subtype,
  color,
  season
from public.wardrobe
order by type_order, subtype_order, name;

insert into public.wardrobe
  (name, product_name, brand, type, subtype, color, season, capsule, notes)
values
  ('white tank', 'Ribbed cotton tank', 'Example Studio', 'top', 'tank', 'white', 'summer', true, 'Clean base layer for warm-weather outfits.'),
  ('black baby tee', 'Fitted short-sleeve tee', 'Everyday Label', 'top', 'baby tee', 'black', 'all-season', true, 'Useful with denim, skirts, trousers, and under jackets.'),
  ('blue button-down', 'Relaxed cotton shirt', 'Market Sample', 'top', 'shirt', 'blue stripe', 'all-season', true, 'A polished layer that still feels casual.'),
  ('black trousers', 'Straight-leg trouser', 'Example Studio', 'bottom', 'pants', 'black', 'all-season', true, 'Anchor piece for work, dinners, and travel.'),
  ('denim shorts', 'High-rise denim short', 'Denim Sample', 'bottom', 'shorts', 'medium blue', 'summer', false, 'Good seasonal piece; less essential year-round.'),
  ('linen jacket', 'Lightweight linen jacket', 'Market Sample', 'outerwear', 'jacket', 'natural', 'summer', true, 'Light structure without feeling too formal.'),
  ('black slip dress', 'Midi slip dress', 'Occasion Label', 'dress', 'dress', 'black', 'all-season', true, 'Easy dinner, travel, and event piece.'),
  ('silver flats', 'Leather ballet flat', 'Shoe Sample', 'shoes', 'flats', 'silver', 'all-season', true, 'Adds polish without needing a heel.');

select name, brand, capsule, type
from public.wardrobe
order by type_order, subtype_order, name;
