create table if not exists public.wardrobe (
  id bigint generated by default as identity primary key,
  name text not null,
  product_name text,
  brand text,
  type text not null check (type in ('top', 'bottom', 'outerwear', 'dress', 'shoes')),
  subtype text,
  color text,
  season text,
  capsule boolean not null default false,
  notes text,
  type_order int generated always as (
    case type
      when 'top' then 1
      when 'bottom' then 2
      when 'outerwear' then 3
      when 'dress' then 4
      when 'shoes' then 5
      else 999
    end
  ) stored,
  created_at timestamptz not null default now()
);
